metadata:
  title: NodePiece+Rotate
  origin: Learn OGBBIOKG Dataset with NodePiece + RotatE as described by Galkin et al., 2022
pipeline:
  random_seed: 42
  dataset: ogbbiokg
  dataset_kwargs:
    create_inverse_triples: True
    cache_root: "src/"
  evaluator_kwargs:
    filtered: true
  loss: NSSALoss
  loss_kwargs:
    margin: 50
    adversarial_temperature: 1.0
    reduction: 'mean'
  model: NodePiece
  model_kwargs:
    entity_initializer: xavier_uniform_
    relation_initializer: init_phases
    relation_constrainer: complex_normalize
    embedding_dim: 200   # for both anchors and relations
    interaction: RotatEInteraction
    aggregation: mlp
    tokenizers: ['AnchorTokenizer', 'RelationTokenizer']
    num_tokens: [10, 6]  # 20 anchors, 12 relations
    tokenizers_kwargs:
      - selection: MixtureAnchorSelection
        searcher: CSGraphAnchorSearcher
        selection_kwargs:
          selections: ['Degree', 'PageRank', 'Random']
          ratios: [0.4, 0.4, 0.2]
          num_anchors: 100
      - {} # no params for RelationTokenizer

  optimizer: Adam
  optimizer_kwargs:
    lr: 0.0001
  negative_sampler: basic
  negative_sampler_kwargs: 
    num_negs_per_pos: 128
  training_kwargs:
    batch_size: 512
    num_epochs: 10
  training_loop: SLCWA