model_name: "DualE"
datasets:
  - dataset: "yago3-10"
    parameters:
      learning_rate: 0.1
      l1_flag: True
      hidden_size: 200
      batch_size: 100
      epochs: 200
      margin: 1.0
      optimizer: "adagrad"
      sampling: "bern"
      neg_rate: 1
      lmbda: 0.1
      alpha: 1.0
      patience: 100
  
  - dataset: "ogbbiokg"
    parameters:
      learning_rate: 0.001
      l1_flag: True
      hidden_size: 2000
      batch_size: 512
      epochs: 100
      margin: 20.0
      optimizer: "adam"
      sampling: "bern"
      neg_rate: 4
      lmbda: 0.1
      alpha: 1.0
      patience: 100